title: Field Noise
description: Field Noise is a podcast about the audible world.
baseurl: ""
url: "http://www.fieldnoise.com"

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Podcast Feed settings
title:          Field Noise
email:          craig@fieldnoise.com
description:    "Field Noise is a podcast about the audible world."
subtitle:       "Sound, history, and our everyday lives"
url:            http://fieldnoise.com/
language:       en-us
author:         Craig Eley
copyright:      "CC BY 4.0"

feed:
  collections:
    episodes:
      path: "/episodes.xml"

collections:
  episodes:
